# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
# windows build
- job: windowsLatestBuild
  displayName: Windows Latest Build
  pool:
    vmImage: 'windows-latest'
  steps:
  # use nodeJS 10
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
  - task: CmdLine@2
    displayName: Install Node Modules
    inputs:
      script: 'npm install'
  - task: CmdLine@2
    displayName: Pack application
    inputs:
      script: 'npm run pack:windows'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: './dist/win-unpacked/'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-windows.zip'
      replaceExistingArchive: true
  # publish artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Windows Build ($(Build.BuildId))'
      publishLocation: 'Container'


# macOS build
- job: macosLatestBuild
  displayName: MacOS Latest Build
  pool:
    vmImage: 'macOS-latest'
  steps:
  # use nodeJS 10
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
  - task: CmdLine@2
    displayName: Install Node Modules
    inputs:
      script: 'npm install'
  - task: CmdLine@2
    displayName: Pack application
    inputs:
      script: 'npm run pack:macos'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: './dist/mac/'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-macos.zip'
      replaceExistingArchive: true
  # publish artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'MacOS Build ($(Build.BuildId))'
      publishLocation: 'Container'